package com.tencent.mm.g.b.a;

import com.tencent.mm.plugin.report.a;
import com.tencent.mm.sdk.platformtools.bi;
import java.util.Arrays;

public final class h extends a {
    private long cgH = 0;
    private long cgI = 0;
    private String cgN = "";
    private long cgP = 0;
    private long cgQ = 0;
    private long cgT = 0;
    private long cgU = 0;
    private long cgV = 0;
    private long cgW = 0;
    private long cgX = 0;
    private long cgY = 0;
    private long cgZ = 0;
    private String chB = "";
    private int chC = 0;
    private long chD = 0;
    private String chN = "";
    private String chO = "";
    private long chP = 0;
    private int chQ = 0;
    private String chR = "";
    private String chS = "";
    private long cha = 0;
    private long chb = 0;
    private long chc = 0;
    private long chd = 0;
    private int chg = 0;
    private long chh = 0;
    private long chi = 0;
    private long chj = 0;
    private long chk = 0;
    private int chl = 0;
    private long chm = 0;
    private long chn = 0;
    private long cho = 0;
    private long chp = 0;
    private long chq = 0;
    private long chr = 0;
    private long chs = 0;
    private int cht = 0;
    private int chu = 0;
    private long chv = 0;
    private int chw = 0;

    public h(String str) {
        if (str != null) {
            Object split = str.split(",");
            if (split != null) {
                Object obj;
                if (split.length < 42) {
                    obj = new String[42];
                    Arrays.fill(obj, 0, 42, "");
                    System.arraycopy(split, 0, obj, 0, split.length);
                } else {
                    obj = split;
                }
                this.chN = obj[0];
                this.chO = obj[1];
                this.cgT = bi.getLong(obj[2], 0);
                this.cgH = bi.getLong(obj[3], 0);
                this.cgU = bi.getLong(obj[4], 0);
                this.cgV = bi.getLong(obj[5], 0);
                this.cgW = bi.getLong(obj[6], 0);
                this.cgX = bi.getLong(obj[7], 0);
                this.cgY = bi.getLong(obj[8], 0);
                this.cgZ = bi.getLong(obj[9], 0);
                this.cha = bi.getLong(obj[10], 0);
                this.chb = bi.getLong(obj[11], 0);
                this.chc = bi.getLong(obj[12], 0);
                this.chd = bi.getLong(obj[13], 0);
                this.chP = bi.getLong(obj[14], 0);
                this.chQ = bi.getInt(obj[15], 0);
                this.chg = bi.getInt(obj[16], 0);
                this.chh = bi.getLong(obj[17], 0);
                this.chi = bi.getLong(obj[18], 0);
                this.chj = bi.getLong(obj[19], 0);
                this.chk = bi.getLong(obj[20], 0);
                this.chl = bi.getInt(obj[21], 0);
                this.chm = bi.getLong(obj[22], 0);
                this.chn = bi.getLong(obj[23], 0);
                this.cho = bi.getLong(obj[24], 0);
                this.chp = bi.getLong(obj[25], 0);
                this.chq = bi.getLong(obj[26], 0);
                this.chr = bi.getLong(obj[27], 0);
                this.chs = bi.getLong(obj[28], 0);
                this.cht = bi.getInt(obj[29], 0);
                this.chu = bi.getInt(obj[30], 0);
                this.chv = bi.getLong(obj[31], 0);
                this.chw = bi.getInt(obj[32], 0);
                this.cgI = bi.getLong(obj[33], 0);
                this.chR = obj[34];
                this.cgN = obj[35];
                this.chS = obj[36];
                this.chB = obj[37];
                this.chC = bi.getInt(obj[38], 0);
                this.chD = bi.getLong(obj[39], 0);
                this.cgP = bi.getLong(obj[40], 0);
                this.cgQ = bi.getLong(obj[41], 0);
            }
        }
    }

    public final int getId() {
        return 13790;
    }

    public final String wE() {
        String str = ",";
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append(this.chN);
        stringBuffer.append(str);
        stringBuffer.append(this.chO);
        stringBuffer.append(str);
        stringBuffer.append(this.cgT);
        stringBuffer.append(str);
        stringBuffer.append(this.cgH);
        stringBuffer.append(str);
        stringBuffer.append(this.cgU);
        stringBuffer.append(str);
        stringBuffer.append(this.cgV);
        stringBuffer.append(str);
        stringBuffer.append(this.cgW);
        stringBuffer.append(str);
        stringBuffer.append(this.cgX);
        stringBuffer.append(str);
        stringBuffer.append(this.cgY);
        stringBuffer.append(str);
        stringBuffer.append(this.cgZ);
        stringBuffer.append(str);
        stringBuffer.append(this.cha);
        stringBuffer.append(str);
        stringBuffer.append(this.chb);
        stringBuffer.append(str);
        stringBuffer.append(this.chc);
        stringBuffer.append(str);
        stringBuffer.append(this.chd);
        stringBuffer.append(str);
        stringBuffer.append(this.chP);
        stringBuffer.append(str);
        stringBuffer.append(this.chQ);
        stringBuffer.append(str);
        stringBuffer.append(this.chg);
        stringBuffer.append(str);
        stringBuffer.append(this.chh);
        stringBuffer.append(str);
        stringBuffer.append(this.chi);
        stringBuffer.append(str);
        stringBuffer.append(this.chj);
        stringBuffer.append(str);
        stringBuffer.append(this.chk);
        stringBuffer.append(str);
        stringBuffer.append(this.chl);
        stringBuffer.append(str);
        stringBuffer.append(this.chm);
        stringBuffer.append(str);
        stringBuffer.append(this.chn);
        stringBuffer.append(str);
        stringBuffer.append(this.cho);
        stringBuffer.append(str);
        stringBuffer.append(this.chp);
        stringBuffer.append(str);
        stringBuffer.append(this.chq);
        stringBuffer.append(str);
        stringBuffer.append(this.chr);
        stringBuffer.append(str);
        stringBuffer.append(this.chs);
        stringBuffer.append(str);
        stringBuffer.append(this.cht);
        stringBuffer.append(str);
        stringBuffer.append(this.chu);
        stringBuffer.append(str);
        stringBuffer.append(this.chv);
        stringBuffer.append(str);
        stringBuffer.append(this.chw);
        stringBuffer.append(str);
        stringBuffer.append(this.cgI);
        stringBuffer.append(str);
        stringBuffer.append(this.chR);
        stringBuffer.append(str);
        stringBuffer.append(this.cgN);
        stringBuffer.append(str);
        stringBuffer.append(this.chS);
        stringBuffer.append(str);
        stringBuffer.append(this.chB);
        stringBuffer.append(str);
        stringBuffer.append(this.chC);
        stringBuffer.append(str);
        stringBuffer.append(this.chD);
        stringBuffer.append(str);
        stringBuffer.append(this.cgP);
        stringBuffer.append(str);
        stringBuffer.append(this.cgQ);
        str = stringBuffer.toString();
        KD(str);
        return str;
    }

    public final String wF() {
        StringBuffer stringBuffer = new StringBuffer();
        stringBuffer.append("SnsVideoUrl:").append(this.chN);
        stringBuffer.append("\r\n");
        stringBuffer.append("SnsReserved1:").append(this.chO);
        stringBuffer.append("\r\n");
        stringBuffer.append("FileLength:").append(this.cgT);
        stringBuffer.append("\r\n");
        stringBuffer.append("VideoDuration:").append(this.cgH);
        stringBuffer.append("\r\n");
        stringBuffer.append("DownloadLength:").append(this.cgU);
        stringBuffer.append("\r\n");
        stringBuffer.append("PlayDuration:").append(this.cgV);
        stringBuffer.append("\r\n");
        stringBuffer.append("FirstPlayWaitTime:").append(this.cgW);
        stringBuffer.append("\r\n");
        stringBuffer.append("MoovWaitTime:").append(this.cgX);
        stringBuffer.append("\r\n");
        stringBuffer.append("BlockCount:").append(this.cgY);
        stringBuffer.append("\r\n");
        stringBuffer.append("RegainAvgTime:").append(this.cgZ);
        stringBuffer.append("\r\n");
        stringBuffer.append("NetworkType:").append(this.cha);
        stringBuffer.append("\r\n");
        stringBuffer.append("DownloadType:").append(this.chb);
        stringBuffer.append("\r\n");
        stringBuffer.append("StartDownloadTime:").append(this.chc);
        stringBuffer.append("\r\n");
        stringBuffer.append("EndDownloadTime:").append(this.chd);
        stringBuffer.append("\r\n");
        stringBuffer.append("ChatName:").append(this.chP);
        stringBuffer.append("\r\n");
        stringBuffer.append("HttpStatusCode:").append(this.chQ);
        stringBuffer.append("\r\n");
        stringBuffer.append("RetCode:").append(this.chg);
        stringBuffer.append("\r\n");
        stringBuffer.append("EnterQueueTime:").append(this.chh);
        stringBuffer.append("\r\n");
        stringBuffer.append("FirstReqCostTime:").append(this.chi);
        stringBuffer.append("\r\n");
        stringBuffer.append("FirstReqSize:").append(this.chj);
        stringBuffer.append("\r\n");
        stringBuffer.append("FirstReqDownloadSize:").append(this.chk);
        stringBuffer.append("\r\n");
        stringBuffer.append("FirstReqCompleted:").append(this.chl);
        stringBuffer.append("\r\n");
        stringBuffer.append("AvgSpeed:").append(this.chm);
        stringBuffer.append("\r\n");
        stringBuffer.append("AvgConnectCost:").append(this.chn);
        stringBuffer.append("\r\n");
        stringBuffer.append("FirstConnectCostTime:").append(this.cho);
        stringBuffer.append("\r\n");
        stringBuffer.append("NetConnectTimes:").append(this.chp);
        stringBuffer.append("\r\n");
        stringBuffer.append("MoovReqTimes:").append(this.chq);
        stringBuffer.append("\r\n");
        stringBuffer.append("MoovCostTime:").append(this.chr);
        stringBuffer.append("\r\n");
        stringBuffer.append("MoovSize:").append(this.chs);
        stringBuffer.append("\r\n");
        stringBuffer.append("MoovCompleted:").append(this.cht);
        stringBuffer.append("\r\n");
        stringBuffer.append("MoovFailReason:").append(this.chu);
        stringBuffer.append("\r\n");
        stringBuffer.append("UiStayTime:").append(this.chv);
        stringBuffer.append("\r\n");
        stringBuffer.append("PlayErrorCode:").append(this.chw);
        stringBuffer.append("\r\n");
        stringBuffer.append("VideoBitrate:").append(this.cgI);
        stringBuffer.append("\r\n");
        stringBuffer.append("postname:").append(this.chR);
        stringBuffer.append("\r\n");
        stringBuffer.append("CDNIp:").append(this.cgN);
        stringBuffer.append("\r\n");
        stringBuffer.append("SnsPublishid:").append(this.chS);
        stringBuffer.append("\r\n");
        stringBuffer.append("XClientIp:").append(this.chB);
        stringBuffer.append("\r\n");
        stringBuffer.append("IsCrossNet:").append(this.chC);
        stringBuffer.append("\r\n");
        stringBuffer.append("MoovPosition:").append(this.chD);
        stringBuffer.append("\r\n");
        stringBuffer.append("HadPreloadSize:").append(this.cgP);
        stringBuffer.append("\r\n");
        stringBuffer.append("HadPreloadCompletion:").append(this.cgQ);
        return stringBuffer.toString();
    }
}
