package com.tencent.mm.plugin.sns.ui.a;

import android.view.View;
import android.view.ViewGroup;
import android.view.ViewStub;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.tencent.mm.plugin.sns.ui.AsyncNormalTextView;
import com.tencent.mm.plugin.sns.ui.AsyncTextView;
import com.tencent.mm.plugin.sns.ui.MaskTextView;
import com.tencent.mm.plugin.sns.ui.PhotosContent;
import com.tencent.mm.plugin.sns.ui.SnsTranslateResultView;
import com.tencent.mm.plugin.sns.ui.TagImageView;
import com.tencent.mm.plugin.sns.ui.a.h.a;
import com.tencent.mm.plugin.sns.ui.ak;
import com.tencent.mm.plugin.sns.ui.bf;
import com.tencent.mm.plugin.sns.ui.widget.SnsCardAdTagListView;
import com.tencent.mm.protocal.c.atf;
import com.tencent.mm.protocal.c.boy;
import com.tencent.mm.protocal.c.bsu;

public class a$c {
    public String bKW;
    public String bSZ;
    public TextView eBO;
    public ImageView eCl;
    public String fvT;
    public int hER;
    public TextView hrV;
    public View jEz;
    public boolean jLu;
    public TextView nEJ;
    public atf nJn;
    public LinearLayout nKX;
    public ImageView nLz;
    public TextView nNC;
    public int nUp = 210;
    public TextView nZV;
    public boy nib;
    public boolean nkG;
    public bf nkH;
    public TextView nmi;
    public View oaa;
    public long oiF;
    public int oiG;
    public AsyncTextView oiH;
    public ImageView oiI;
    public ViewGroup oiJ;
    public AsyncNormalTextView oiK;
    public TextView oiL;
    public TextView oiM;
    public SnsTranslateResultView oiN;
    public View oiO;
    public LinearLayout oiP;
    public ViewStub oiQ;
    public boolean oiR = false;
    public TextView oiS;
    public TagImageView oiT;
    public TextView oiU;
    public int oiV = 0;
    public TextView oiW;
    public AsyncTextView oiX;
    public AsyncTextView oiY;
    public TextView oiZ;
    public ViewStub ojA;
    public boolean ojB = false;
    public View ojC;
    public ImageView ojD;
    public boolean ojE = false;
    ViewStub ojF;
    boolean ojG = false;
    public ak ojH = new ak();
    public View ojI;
    public boolean ojJ = false;
    public a ojK;
    public ak ojL = new ak();
    public bsu ojM;
    public com.tencent.mm.l.a ojN;
    public View ojO;
    public a ojP;
    public ViewStub ojQ;
    public View ojR;
    public MaskTextView ojS;
    public View ojT;
    TextView ojU;
    public String ojV;
    public View ojW;
    public Button ojX;
    public Button ojY;
    public View ojZ;
    public View oja;
    public ImageView ojb;
    public View ojc;
    public MaskTextView ojd;
    public LinearLayout oje;
    public LinearLayout ojf;
    public View ojg;
    public LinearLayout ojh;
    public PhotosContent oji;
    public View ojj;
    public ViewStub ojk;
    public boolean ojl = false;
    public ViewStub ojm;
    public ViewStub ojn;
    public View ojo = null;
    public boolean ojp = false;
    public boolean ojq = false;
    public ViewStub ojr;
    public boolean ojs = false;
    public View ojt;
    public LinearLayout oju;
    public TextView ojv;
    public ViewStub ojw;
    public boolean ojx = false;
    public View ojy;
    public LinearLayout ojz;
    public ImageView oka;
    public TextView okb;
    public SnsCardAdTagListView okc;
    public int position;
}
