package com.tencent.mm.plugin.game.wepkg.a;

import com.tencent.mm.g.c.ey;
import com.tencent.mm.sdk.e.c.a;
import java.lang.reflect.Field;

public final class c extends ey {
    public static final a dzU;

    static {
        a aVar = new a();
        aVar.sKy = new Field[25];
        aVar.columns = new String[26];
        StringBuilder stringBuilder = new StringBuilder();
        aVar.columns[0] = "pkgId";
        aVar.sKA.put("pkgId", "TEXT PRIMARY KEY ");
        stringBuilder.append(" pkgId TEXT PRIMARY KEY ");
        stringBuilder.append(", ");
        aVar.sKz = "pkgId";
        aVar.columns[1] = "appId";
        aVar.sKA.put("appId", "TEXT");
        stringBuilder.append(" appId TEXT");
        stringBuilder.append(", ");
        aVar.columns[2] = "version";
        aVar.sKA.put("version", "TEXT");
        stringBuilder.append(" version TEXT");
        stringBuilder.append(", ");
        aVar.columns[3] = "pkgPath";
        aVar.sKA.put("pkgPath", "TEXT");
        stringBuilder.append(" pkgPath TEXT");
        stringBuilder.append(", ");
        aVar.columns[4] = "disableWvCache";
        aVar.sKA.put("disableWvCache", "INTEGER default 'true' ");
        stringBuilder.append(" disableWvCache INTEGER default 'true' ");
        stringBuilder.append(", ");
        aVar.columns[5] = "clearPkgTime";
        aVar.sKA.put("clearPkgTime", "LONG");
        stringBuilder.append(" clearPkgTime LONG");
        stringBuilder.append(", ");
        aVar.columns[6] = "checkIntervalTime";
        aVar.sKA.put("checkIntervalTime", "LONG");
        stringBuilder.append(" checkIntervalTime LONG");
        stringBuilder.append(", ");
        aVar.columns[7] = "packMethod";
        aVar.sKA.put("packMethod", "INTEGER");
        stringBuilder.append(" packMethod INTEGER");
        stringBuilder.append(", ");
        aVar.columns[8] = "domain";
        aVar.sKA.put("domain", "TEXT");
        stringBuilder.append(" domain TEXT");
        stringBuilder.append(", ");
        aVar.columns[9] = "md5";
        aVar.sKA.put("md5", "TEXT");
        stringBuilder.append(" md5 TEXT");
        stringBuilder.append(", ");
        aVar.columns[10] = "downloadUrl";
        aVar.sKA.put("downloadUrl", "TEXT");
        stringBuilder.append(" downloadUrl TEXT");
        stringBuilder.append(", ");
        aVar.columns[11] = "pkgSize";
        aVar.sKA.put("pkgSize", "INTEGER");
        stringBuilder.append(" pkgSize INTEGER");
        stringBuilder.append(", ");
        aVar.columns[12] = "downloadNetType";
        aVar.sKA.put("downloadNetType", "INTEGER");
        stringBuilder.append(" downloadNetType INTEGER");
        stringBuilder.append(", ");
        aVar.columns[13] = "nextCheckTime";
        aVar.sKA.put("nextCheckTime", "LONG");
        stringBuilder.append(" nextCheckTime LONG");
        stringBuilder.append(", ");
        aVar.columns[14] = "createTime";
        aVar.sKA.put("createTime", "LONG");
        stringBuilder.append(" createTime LONG");
        stringBuilder.append(", ");
        aVar.columns[15] = "accessTime";
        aVar.sKA.put("accessTime", "LONG default '0' ");
        stringBuilder.append(" accessTime LONG default '0' ");
        stringBuilder.append(", ");
        aVar.columns[16] = "charset";
        aVar.sKA.put("charset", "TEXT default 'UTF-8' ");
        stringBuilder.append(" charset TEXT default 'UTF-8' ");
        stringBuilder.append(", ");
        aVar.columns[17] = "bigPackageReady";
        aVar.sKA.put("bigPackageReady", "INTEGER default 'false' ");
        stringBuilder.append(" bigPackageReady INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[18] = "preloadFilesReady";
        aVar.sKA.put("preloadFilesReady", "INTEGER default 'false' ");
        stringBuilder.append(" preloadFilesReady INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[19] = "preloadFilesAtomic";
        aVar.sKA.put("preloadFilesAtomic", "INTEGER default 'false' ");
        stringBuilder.append(" preloadFilesAtomic INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[20] = "autoDownloadCount";
        aVar.sKA.put("autoDownloadCount", "INTEGER default '0' ");
        stringBuilder.append(" autoDownloadCount INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[21] = "disable";
        aVar.sKA.put("disable", "INTEGER default 'false' ");
        stringBuilder.append(" disable INTEGER default 'false' ");
        stringBuilder.append(", ");
        aVar.columns[22] = "totalDownloadCount";
        aVar.sKA.put("totalDownloadCount", "INTEGER default '0' ");
        stringBuilder.append(" totalDownloadCount INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[23] = "packageDownloadCount";
        aVar.sKA.put("packageDownloadCount", "INTEGER default '0' ");
        stringBuilder.append(" packageDownloadCount INTEGER default '0' ");
        stringBuilder.append(", ");
        aVar.columns[24] = "downloadTriggerType";
        aVar.sKA.put("downloadTriggerType", "INTEGER default '-1' ");
        stringBuilder.append(" downloadTriggerType INTEGER default '-1' ");
        aVar.columns[25] = "rowid";
        aVar.sql = stringBuilder.toString();
        dzU = aVar;
    }

    protected final a AX() {
        return dzU;
    }
}
