package com.tencent.mm.plugin.sns.h;

import android.os.Process;
import com.tencent.mm.model.s;
import com.tencent.mm.modelsns.d;
import com.tencent.mm.plugin.report.service.h;
import com.tencent.mm.plugin.sns.data.i;
import com.tencent.mm.plugin.sns.model.af;
import com.tencent.mm.plugin.sns.model.aj;
import com.tencent.mm.plugin.sns.storage.n;
import com.tencent.mm.protocal.c.vu;
import com.tencent.mm.sdk.b.a;
import com.tencent.mm.sdk.platformtools.x;

class b$2 implements Runnable {
    final /* synthetic */ int nxA;
    final /* synthetic */ b nxz;

    public b$2(b bVar, int i) {
        this.nxz = bVar;
        this.nxA = i;
    }

    public final void run() {
        int myTid = Process.myTid();
        x.i("MicroMsg.SnsBrowseInfoHelper", "summersns report tid[%d] osTid[%d], prior[%d][%d]", new Object[]{Long.valueOf(Thread.currentThread().getId()), Integer.valueOf(myTid), Integer.valueOf(Thread.currentThread().getPriority()), Integer.valueOf(Process.getThreadPriority(myTid))});
        long currentTimeMillis = System.currentTimeMillis();
        b bVar = this.nxz;
        int i = this.nxA;
        if (i != -1) {
            n wy = aj.wy(i);
            if (wy != null) {
                String g = i.g(wy);
                bVar.nvS = g;
                vu bAV = af.bys().Np("@__weixintimtline").bAV();
                if (bAV.rzb == 0 || i.eG(bAV.rzb).compareTo(g) <= 0) {
                    bVar.ih(false);
                } else {
                    bVar.ih(true);
                }
            }
        }
        i = s.Hw();
        d dVar = new d();
        dVar.r("20BrowseTime", bVar.nvD + ",");
        dVar.r("21BrowseFeedCount", bVar.nvE + ",");
        dVar.r("22CommentOrLikeFeedCount", bVar.nvF + ",");
        dVar.r("23ClickFeedCount", bVar.nvG + ",");
        dVar.r("24ClickAlbumCount", bVar.nvH + ",");
        dVar.r("25PostFeedCount", bVar.nvI + ",");
        dVar.r("26ExposeFeedCount", bVar.nwY.size() + ",");
        dVar.r("27FavFeedCount", bVar.nwZ.size() + ",");
        dVar.r("28BlackListFriendCount", bVar.nvL + ",");
        dVar.r("29OutsiderFriendCount", bVar.nvM + ",");
        dVar.r("30BrowseNewFeedCount", bVar.nvN + ",");
        dVar.r("31HasNewSnsMsgWhenEntrance", bVar.nvO + ",");
        dVar.r("32HasNewChatMsgWhenExit", bVar.nvP + ",");
        dVar.r("33StartBrowseSnsObjectId", bVar.nvQ + ",");
        dVar.r("34EndBrowseSnsObjectId", bVar.nvR + ",");
        dVar.r("35NextBrowseSnsObjectId", bVar.nvS + ",");
        dVar.r("36HasNewFeedInServer", bVar.nvT + ",");
        dVar.r("37BrowseBrandUrlFeedCount", bVar.nvU + ",");
        dVar.r("38BrowseNotBrandUrlFeedCount", bVar.nvV + ",");
        dVar.r("39BrowseTextFeedCount", bVar.nvW + ",");
        dVar.r("40BrowseImageFeedCount", bVar.nvX + ",");
        dVar.r("41BrowseSightFeedCount", bVar.nvY + ",");
        dVar.r("42BrowseAdFeedCount", bVar.nvZ + ",");
        dVar.r("43BrowseMusicFeedCount", bVar.nwa + ",");
        dVar.r("44contactCount", i + ",");
        dVar.r("BrowseVideoFeedCount45", bVar.nwb + ",");
        dVar.r("ClickBrandUrlFeedCount46", bVar.nwc + ",");
        dVar.r("ClickNotBrandUrlFeedCount47", bVar.nwd + ",");
        dVar.r("ClickImageFeedCount48", bVar.nwe + ",");
        dVar.r("ClickSightFeedCount49", bVar.nwf + ",");
        dVar.r("ClickMusicFeedCount50", bVar.nwg + ",");
        dVar.r("ClickVideoFeedCount51", bVar.nwh + ",");
        dVar.r("BrowseOtherFeedCount52", bVar.nwi + ",");
        dVar.r("BrowserStreamVideoFeedCount53", bVar.nwj + ",");
        dVar.r("ClickStreamVideoCount54", bVar.nwk + ",");
        dVar.r("ClickAdFeed55", bVar.nwl + ",");
        dVar.r("56BackGroundTime", bVar.nwm + ",");
        dVar.r("57BrowseTimeLineTime", bVar.nwo + ",");
        dVar.r("58BrowseMyAlbumTime", bVar.nwq + ",");
        dVar.r("59BrowseOtherAlbumTime", bVar.nws + ",");
        dVar.r("60BrowseMessageListTime", bVar.nwu + ",");
        dVar.r("61ClickNewPostTime", bVar.nww + ",");
        dVar.r("62BrowseFullScreenImageTime", bVar.nwy + ",");
        dVar.r("63BrowseFullScreenSightTime", bVar.nwA + ",");
        dVar.r("64BrowseMPArticleTime", bVar.nwC + ",");
        dVar.r("65BrowseExternalArticleTime", bVar.nwE + ",");
        dVar.r("66BrowseFullScreenAdImageTime", bVar.nwG + ",");
        dVar.r("67BrowseAdSightTime", "0,");
        dVar.r("68BrowseAdDetailTime", bVar.nwI + ",");
        dVar.r("69BrowseFullScreenAdSightTime", bVar.nwK + ",");
        dVar.r("70BrowseFullScreenAdLongVideoTime", bVar.nwM + ",");
        dVar.r("71BrowseForwardAdLongVideoTime", bVar.nwO + ",");
        dVar.r("72StartBrowseTime", bVar.nxy + ",");
        dVar.r("73ClickFeedIdList", b.f(bVar.nwX) + ",");
        dVar.r("74ExposeFeedIdList", b.f(bVar.nwY) + ",");
        dVar.r("75FavFeedIdList", b.f(bVar.nwZ) + ",");
        dVar.r("76ClickAlbumUserList", b.f(bVar.nxf) + ",");
        dVar.r("77ForwardFeedIdList", b.f(bVar.nxa) + ",");
        dVar.r("78ClickAvatarFeedIdList", b.f(bVar.nxb) + ",");
        dVar.r("79ClickNickNameFeedIdList", b.f(bVar.nxc) + ",");
        dVar.r("80ForwardToSingleChatFeedIdList", b.f(bVar.nxd) + ",");
        dVar.r("81ForwardToChatRoomFeedIdList", b.f(bVar.nxe) + ",");
        dVar.r("82FeedUpdateNotification", bVar.cXZ + ",");
        dVar.r("83abandon", ",");
        dVar.r("84abandon", ",");
        dVar.r("85LastestUnReadFeedId", bVar.nwQ + ",");
        dVar.r("86UnReadMsgCount", bVar.nwR + ",");
        dVar.r("87BrowseAdCanvasPageTime", bVar.nwS + ",");
        dVar.r("88BrowseForwardAdCanvasTime", bVar.nwU + ",");
        x.v("MicroMsg.SnsBrowseInfoHelper", "report logbuffer(12076): " + dVar.wF());
        h.mEJ.h(12076, new Object[]{dVar});
        a.sFg.c(bVar.cXu);
        bVar.nvD = 0;
        bVar.nvE = 0;
        bVar.nvF = 0;
        bVar.nvG = 0;
        bVar.nvH = 0;
        bVar.nvI = 0;
        bVar.nvJ = 0;
        bVar.nvK = 0;
        bVar.nvL = 0;
        bVar.nvM = 0;
        bVar.nvN = 0;
        bVar.nvO = 0;
        bVar.nvP = 0;
        bVar.nvQ = "";
        bVar.nvR = "";
        bVar.nvS = "";
        bVar.nvT = 0;
        bVar.nvU = 0;
        bVar.nvV = 0;
        bVar.nvW = 0;
        bVar.nvX = 0;
        bVar.nvY = 0;
        bVar.nvZ = 0;
        bVar.nwa = 0;
        bVar.hpo = 0;
        bVar.nwb = 0;
        bVar.nwc = 0;
        bVar.nwd = 0;
        bVar.nwe = 0;
        bVar.nwf = 0;
        bVar.nwg = 0;
        bVar.nwh = 0;
        bVar.nwi = 0;
        bVar.nwj = 0;
        bVar.nwk = 0;
        bVar.nwl = 0;
        bVar.nwm = 0;
        bVar.nwn = 0;
        bVar.nwo = 0;
        bVar.nwp = 0;
        bVar.nwq = 0;
        bVar.nwr = 0;
        bVar.nws = 0;
        bVar.nwt = 0;
        bVar.nwu = 0;
        bVar.nwv = 0;
        bVar.nww = 0;
        bVar.nwx = 0;
        bVar.nwy = 0;
        bVar.nwz = 0;
        bVar.nwA = 0;
        bVar.nwB = 0;
        bVar.nwC = 0;
        bVar.nwD = 0;
        bVar.nwE = 0;
        bVar.nwF = 0;
        bVar.nwG = 0;
        bVar.nwH = 0;
        bVar.nwI = 0;
        bVar.nwJ = 0;
        bVar.nwK = 0;
        bVar.nwL = 0;
        bVar.nwM = 0;
        bVar.nwN = 0;
        bVar.nwO = 0;
        bVar.nwP = 0;
        bVar.nwX.clear();
        bVar.nwY.clear();
        bVar.nwZ.clear();
        bVar.nxa.clear();
        bVar.nxb.clear();
        bVar.nxc.clear();
        bVar.nxd.clear();
        bVar.nxe.clear();
        bVar.cXZ = 0;
        bVar.nwQ = "";
        bVar.nwR = 0;
        x.i("MicroMsg.SnsBrowseInfoHelper", "summersns report take[%d]ms", new Object[]{Long.valueOf(System.currentTimeMillis() - currentTimeMillis)});
    }
}
